// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArticleDetailState.
const (
	ArticleDetailStateActive  ArticleDetailState = "active"
	ArticleDetailStateTrashed ArticleDetailState = "trashed"
)

// Valid indicates whether the value is a known member of the ArticleDetailState enum.
func (e ArticleDetailState) Valid() bool {
	switch e {
	case ArticleDetailStateActive:
		return true
	case ArticleDetailStateTrashed:
		return true
	default:
		return false
	}
}

// Defines values for ArticleSummaryState.
const (
	ArticleSummaryStateActive  ArticleSummaryState = "active"
	ArticleSummaryStateTrashed ArticleSummaryState = "trashed"
)

// Valid indicates whether the value is a known member of the ArticleSummaryState enum.
func (e ArticleSummaryState) Valid() bool {
	switch e {
	case ArticleSummaryStateActive:
		return true
	case ArticleSummaryStateTrashed:
		return true
	default:
		return false
	}
}

// Defines values for CreateReleaseRequestMode.
const (
	PublishArticle   CreateReleaseRequestMode = "publish_article"
	PublishSettings  CreateReleaseRequestMode = "publish_settings"
	UnpublishArticle CreateReleaseRequestMode = "unpublish_article"
)

// Valid indicates whether the value is a known member of the CreateReleaseRequestMode enum.
func (e CreateReleaseRequestMode) Valid() bool {
	switch e {
	case PublishArticle:
		return true
	case PublishSettings:
		return true
	case UnpublishArticle:
		return true
	default:
		return false
	}
}

// Defines values for DraftViewReason.
const (
	Draft DraftViewReason = "draft"
)

// Valid indicates whether the value is a known member of the DraftViewReason enum.
func (e DraftViewReason) Valid() bool {
	switch e {
	case Draft:
		return true
	default:
		return false
	}
}

// Defines values for DraftViewStatus.
const (
	Editing DraftViewStatus = "editing"
)

// Valid indicates whether the value is a known member of the DraftViewStatus enum.
func (e DraftViewStatus) Valid() bool {
	switch e {
	case Editing:
		return true
	default:
		return false
	}
}

// Defines values for JenkinsCallbackRequestStatus.
const (
	JenkinsCallbackRequestStatusBuilding  JenkinsCallbackRequestStatus = "building"
	JenkinsCallbackRequestStatusDeploying JenkinsCallbackRequestStatus = "deploying"
	JenkinsCallbackRequestStatusFailed    JenkinsCallbackRequestStatus = "failed"
	JenkinsCallbackRequestStatusQueued    JenkinsCallbackRequestStatus = "queued"
	JenkinsCallbackRequestStatusSuccess   JenkinsCallbackRequestStatus = "success"
)

// Valid indicates whether the value is a known member of the JenkinsCallbackRequestStatus enum.
func (e JenkinsCallbackRequestStatus) Valid() bool {
	switch e {
	case JenkinsCallbackRequestStatusBuilding:
		return true
	case JenkinsCallbackRequestStatusDeploying:
		return true
	case JenkinsCallbackRequestStatusFailed:
		return true
	case JenkinsCallbackRequestStatusQueued:
		return true
	case JenkinsCallbackRequestStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for MediaReferencePurpose.
const (
	Content MediaReferencePurpose = "content"
	Cover   MediaReferencePurpose = "cover"
)

// Valid indicates whether the value is a known member of the MediaReferencePurpose enum.
func (e MediaReferencePurpose) Valid() bool {
	switch e {
	case Content:
		return true
	case Cover:
		return true
	default:
		return false
	}
}

// Defines values for MediaViewMimeType.
const (
	Imagegif  MediaViewMimeType = "image/gif"
	Imagejpeg MediaViewMimeType = "image/jpeg"
	Imagepng  MediaViewMimeType = "image/png"
	Imagewebp MediaViewMimeType = "image/webp"
)

// Valid indicates whether the value is a known member of the MediaViewMimeType enum.
func (e MediaViewMimeType) Valid() bool {
	switch e {
	case Imagegif:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for MediaViewState.
const (
	MediaViewStateActive MediaViewState = "active"
)

// Valid indicates whether the value is a known member of the MediaViewState enum.
func (e MediaViewState) Valid() bool {
	switch e {
	case MediaViewStateActive:
		return true
	default:
		return false
	}
}

// Defines values for PublishJobViewStatus.
const (
	PublishJobViewStatusBuilding  PublishJobViewStatus = "building"
	PublishJobViewStatusDeploying PublishJobViewStatus = "deploying"
	PublishJobViewStatusFailed    PublishJobViewStatus = "failed"
	PublishJobViewStatusPending   PublishJobViewStatus = "pending"
	PublishJobViewStatusQueued    PublishJobViewStatus = "queued"
	PublishJobViewStatusSuccess   PublishJobViewStatus = "success"
)

// Valid indicates whether the value is a known member of the PublishJobViewStatus enum.
func (e PublishJobViewStatus) Valid() bool {
	switch e {
	case PublishJobViewStatusBuilding:
		return true
	case PublishJobViewStatusDeploying:
		return true
	case PublishJobViewStatusFailed:
		return true
	case PublishJobViewStatusPending:
		return true
	case PublishJobViewStatusQueued:
		return true
	case PublishJobViewStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseBundleSchemaVersion.
const (
	N1 ReleaseBundleSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the ReleaseBundleSchemaVersion enum.
func (e ReleaseBundleSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseViewStatus.
const (
	ReleaseViewStatusFailed  ReleaseViewStatus = "failed"
	ReleaseViewStatusQueued  ReleaseViewStatus = "queued"
	ReleaseViewStatusSuccess ReleaseViewStatus = "success"
)

// Valid indicates whether the value is a known member of the ReleaseViewStatus enum.
func (e ReleaseViewStatus) Valid() bool {
	switch e {
	case ReleaseViewStatusFailed:
		return true
	case ReleaseViewStatusQueued:
		return true
	case ReleaseViewStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for RevisionViewReason.
const (
	ManualVersion   RevisionViewReason = "manual_version"
	PublishSnapshot RevisionViewReason = "publish_snapshot"
)

// Valid indicates whether the value is a known member of the RevisionViewReason enum.
func (e RevisionViewReason) Valid() bool {
	switch e {
	case ManualVersion:
		return true
	case PublishSnapshot:
		return true
	default:
		return false
	}
}

// Defines values for RevisionViewStatus.
const (
	Frozen RevisionViewStatus = "frozen"
)

// Valid indicates whether the value is a known member of the RevisionViewStatus enum.
func (e RevisionViewStatus) Valid() bool {
	switch e {
	case Frozen:
		return true
	default:
		return false
	}
}

// Defines values for ListArticlesParamsState.
const (
	ListArticlesParamsStateActive  ListArticlesParamsState = "active"
	ListArticlesParamsStateTrashed ListArticlesParamsState = "trashed"
)

// Valid indicates whether the value is a known member of the ListArticlesParamsState enum.
func (e ListArticlesParamsState) Valid() bool {
	switch e {
	case ListArticlesParamsStateActive:
		return true
	case ListArticlesParamsStateTrashed:
		return true
	default:
		return false
	}
}

// AdminView defines model for AdminView.
type AdminView struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

// ArticleDetail defines model for ArticleDetail.
type ArticleDetail struct {
	CreatedAt           time.Time          `json:"createdAt"`
	Draft               DraftView          `json:"draft"`
	DraftRevisionId     int64              `json:"draftRevisionId"`
	Id                  int64              `json:"id"`
	PublishedRevisionId *int64             `json:"publishedRevisionId"`
	Slug                string             `json:"slug"`
	State               ArticleDetailState `json:"state"`
	UpdatedAt           time.Time          `json:"updatedAt"`
}

// ArticleDetailState defines model for ArticleDetail.State.
type ArticleDetailState string

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []ArticleSummary `json:"items"`
}

// ArticleSummary defines model for ArticleSummary.
type ArticleSummary struct {
	CreatedAt           time.Time           `json:"createdAt"`
	DraftRevisionId     int64               `json:"draftRevisionId"`
	DraftTitle          string              `json:"draftTitle"`
	DraftUpdatedAt      time.Time           `json:"draftUpdatedAt"`
	Id                  int64               `json:"id"`
	PublishedRevisionId *int64              `json:"publishedRevisionId"`
	Slug                string              `json:"slug"`
	State               ArticleSummaryState `json:"state"`
	UpdatedAt           time.Time           `json:"updatedAt"`
}

// ArticleSummaryState defines model for ArticleSummary.State.
type ArticleSummaryState string

// BuilderConfigView defines model for BuilderConfigView.
type BuilderConfigView struct {
	BaseUrl         string `json:"baseUrl"`
	Enabled         bool   `json:"enabled"`
	Id              int64  `json:"id"`
	JobName         string `json:"jobName"`
	Name            string `json:"name"`
	TokenConfigured bool   `json:"tokenConfigured"`
	Username        string `json:"username"`
}

// BundleArticle defines model for BundleArticle.
type BundleArticle struct {
	ArticleId       int64     `json:"articleId"`
	ContentHash     string    `json:"contentHash"`
	ContentMarkdown string    `json:"contentMarkdown"`
	PublishedAt     time.Time `json:"publishedAt"`
	RevisionId      int64     `json:"revisionId"`
	Slug            string    `json:"slug"`
	Summary         string    `json:"summary"`
	Tags            []string  `json:"tags"`
	Title           string    `json:"title"`
}

// BundleSite defines model for BundleSite.
type BundleSite struct {
	AboutMarkdown string       `json:"aboutMarkdown"`
	AuthorBio     string       `json:"authorBio"`
	FilingName    string       `json:"filingName"`
	FilingNumber  string       `json:"filingNumber"`
	Name          string       `json:"name"`
	SocialLinks   []SocialLink `json:"socialLinks"`
}

// BundleTag defines model for BundleTag.
type BundleTag struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateReleaseRequest defines model for CreateReleaseRequest.
type CreateReleaseRequest struct {
	ArticleId *int64                   `json:"articleId"`
	Mode      CreateReleaseRequestMode `json:"mode"`
}

// CreateReleaseRequestMode defines model for CreateReleaseRequest.Mode.
type CreateReleaseRequestMode string

// CreateReleaseResult defines model for CreateReleaseResult.
type CreateReleaseResult struct {
	Job     PublishJobView `json:"job"`
	Release ReleaseView    `json:"release"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Name string `json:"name"`
}

// DraftView defines model for DraftView.
type DraftView struct {
	ArticleId    int64            `json:"articleId"`
	ContentHash  string           `json:"contentHash"`
	ContentMd    string           `json:"contentMd"`
	CoverMediaId *int64           `json:"coverMediaId"`
	CreatedAt    time.Time        `json:"createdAt"`
	Id           int64            `json:"id"`
	LockVersion  int64            `json:"lockVersion"`
	Media        []MediaReference `json:"media"`
	Reason       DraftViewReason  `json:"reason"`
	RevisionNo   int64            `json:"revisionNo"`
	Status       DraftViewStatus  `json:"status"`
	Summary      string           `json:"summary"`
	Tags         []TagSnapshot    `json:"tags"`
	Title        string           `json:"title"`
	UpdatedAt    time.Time        `json:"updatedAt"`
}

// DraftViewReason defines model for DraftView.Reason.
type DraftViewReason string

// DraftViewStatus defines model for DraftView.Status.
type DraftViewStatus string

// HotlinkEntry defines model for HotlinkEntry.
type HotlinkEntry struct {
	Enabled  bool   `json:"enabled"`
	Hostname string `json:"hostname"`
}

// HotlinkSettingsView defines model for HotlinkSettingsView.
type HotlinkSettingsView struct {
	AllowEmptyReferer bool           `json:"allowEmptyReferer"`
	Entries           []HotlinkEntry `json:"entries"`
}

// JenkinsCallbackRequest defines model for JenkinsCallbackRequest.
type JenkinsCallbackRequest struct {
	BuildNumber  int64                        `json:"buildNumber"`
	ErrorSummary string                       `json:"errorSummary"`
	Nonce        string                       `json:"nonce"`
	ReleaseId    int64                        `json:"releaseId"`
	Stage        string                       `json:"stage"`
	Status       JenkinsCallbackRequestStatus `json:"status"`
	Timestamp    time.Time                    `json:"timestamp"`
}

// JenkinsCallbackRequestStatus defines model for JenkinsCallbackRequest.Status.
type JenkinsCallbackRequestStatus string

// LockVersionRequest defines model for LockVersionRequest.
type LockVersionRequest struct {
	LockVersion int64 `json:"lockVersion"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password UTF-8 encoded value must be at most 256 bytes.
	Password string `json:"password"`
	Username string `json:"username"`
}

// MediaReference defines model for MediaReference.
type MediaReference struct {
	MediaId   int64                 `json:"mediaId"`
	Position  int                   `json:"position"`
	PublicKey string                `json:"publicKey"`
	Purpose   MediaReferencePurpose `json:"purpose"`
}

// MediaReferencePurpose defines model for MediaReference.Purpose.
type MediaReferencePurpose string

// MediaUploadPolicy defines model for MediaUploadPolicy.
type MediaUploadPolicy struct {
	AppId     string `json:"appId"`
	Expire    string `json:"expire"`
	FileField string `json:"fileField"`
	Nonce     string `json:"nonce"`
	Policy    string `json:"policy"`
	Signature string `json:"signature"`
	Timestamp string `json:"timestamp"`
	UploadUrl string `json:"uploadUrl"`
}

// MediaView defines model for MediaView.
type MediaView struct {
	CreatedAt    time.Time         `json:"createdAt"`
	FileSize     int64             `json:"fileSize"`
	GfsFileId    int64             `json:"gfsFileId"`
	Height       int               `json:"height"`
	Id           int64             `json:"id"`
	MimeType     MediaViewMimeType `json:"mimeType"`
	OriginalName string            `json:"originalName"`
	PublicKey    string            `json:"publicKey"`
	State        MediaViewState    `json:"state"`
	UpdatedAt    time.Time         `json:"updatedAt"`
	Url          string            `json:"url"`
	Width        int               `json:"width"`
}

// MediaViewMimeType defines model for MediaView.MimeType.
type MediaViewMimeType string

// MediaViewState defines model for MediaView.State.
type MediaViewState string

// PreviewView defines model for PreviewView.
type PreviewView struct {
	Draft DraftView `json:"draft"`
	Slug  string    `json:"slug"`
}

// Problem defines model for Problem.
type Problem struct {
	Code      string `json:"code"`
	RequestId string `json:"requestId"`
	Status    int    `json:"status"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

// PublishJobView defines model for PublishJobView.
type PublishJobView struct {
	BuildNumber  *int64               `json:"buildNumber"`
	BuilderId    int64                `json:"builderId"`
	CreatedAt    time.Time            `json:"createdAt"`
	ErrorSummary string               `json:"errorSummary"`
	FinishedAt   *time.Time           `json:"finishedAt"`
	Id           int64                `json:"id"`
	ReleaseId    int64                `json:"releaseId"`
	Stage        string               `json:"stage"`
	Status       PublishJobViewStatus `json:"status"`
}

// PublishJobViewStatus defines model for PublishJobView.Status.
type PublishJobViewStatus string

// PutBuilderConfigRequest defines model for PutBuilderConfigRequest.
type PutBuilderConfigRequest struct {
	BaseUrl  string  `json:"baseUrl"`
	Enabled  bool    `json:"enabled"`
	JobName  string  `json:"jobName"`
	Name     string  `json:"name"`
	Token    *string `json:"token,omitempty"`
	Username string  `json:"username"`
}

// PutHotlinkSettingsRequest defines model for PutHotlinkSettingsRequest.
type PutHotlinkSettingsRequest struct {
	AllowEmptyReferer bool           `json:"allowEmptyReferer"`
	Entries           []HotlinkEntry `json:"entries"`
}

// PutSiteSettingsRequest defines model for PutSiteSettingsRequest.
type PutSiteSettingsRequest struct {
	AboutMd                string       `json:"aboutMd"`
	AuthorBio              string       `json:"authorBio"`
	AuthorName             string       `json:"authorName"`
	FilingName             string       `json:"filingName"`
	FilingNumber           string       `json:"filingNumber"`
	HomeStatus             string       `json:"homeStatus"`
	LockVersion            int64        `json:"lockVersion"`
	SeoDefaultDescription  string       `json:"seoDefaultDescription"`
	SeoDefaultImageMediaId *int64       `json:"seoDefaultImageMediaId"`
	SeoDefaultTitle        string       `json:"seoDefaultTitle"`
	SiteName               string       `json:"siteName"`
	SocialLinks            []SocialLink `json:"socialLinks"`
}

// RegisterMediaRequest defines model for RegisterMediaRequest.
type RegisterMediaRequest struct {
	GfsFileId    int64  `json:"gfsFileId"`
	OriginalName string `json:"originalName"`
}

// ReleaseBundle defines model for ReleaseBundle.
type ReleaseBundle struct {
	Articles      []BundleArticle            `json:"articles"`
	Checksum      string                     `json:"checksum"`
	GeneratedAt   time.Time                  `json:"generatedAt"`
	ReleaseId     int64                      `json:"releaseId"`
	SchemaVersion ReleaseBundleSchemaVersion `json:"schemaVersion"`
	Site          BundleSite                 `json:"site"`
	Tags          []BundleTag                `json:"tags"`
}

// ReleaseBundleSchemaVersion defines model for ReleaseBundle.SchemaVersion.
type ReleaseBundleSchemaVersion int

// ReleaseList defines model for ReleaseList.
type ReleaseList struct {
	Items []ReleaseView `json:"items"`
}

// ReleaseView defines model for ReleaseView.
type ReleaseView struct {
	Checksum    string     `json:"checksum"`
	CompletedAt *time.Time `json:"completedAt"`
	CreatedAt   time.Time  `json:"createdAt"`
	Id          int64      `json:"id"`

	// Jobs Complete retry history ordered by createdAt descending, then id descending.
	Jobs      []PublishJobView  `json:"jobs"`
	LatestJob PublishJobView    `json:"latestJob"`
	Status    ReleaseViewStatus `json:"status"`
}

// ReleaseViewStatus defines model for ReleaseView.Status.
type ReleaseViewStatus string

// RenameTagRequest defines model for RenameTagRequest.
type RenameTagRequest struct {
	Name string `json:"name"`
}

// RetryReleaseResult The release is the updated aggregate; release.latestJob and release.jobs[0] equal job.
type RetryReleaseResult struct {
	Job     PublishJobView `json:"job"`
	Release ReleaseView    `json:"release"`
}

// RevisionList defines model for RevisionList.
type RevisionList struct {
	Items []RevisionView `json:"items"`
}

// RevisionView defines model for RevisionView.
type RevisionView struct {
	ArticleId    int64              `json:"articleId"`
	ContentHash  string             `json:"contentHash"`
	ContentMd    string             `json:"contentMd"`
	CoverMediaId *int64             `json:"coverMediaId"`
	CreatedAt    time.Time          `json:"createdAt"`
	Id           int64              `json:"id"`
	LockVersion  int64              `json:"lockVersion"`
	Media        []MediaReference   `json:"media"`
	Reason       RevisionViewReason `json:"reason"`
	RevisionNo   int64              `json:"revisionNo"`
	Status       RevisionViewStatus `json:"status"`
	Summary      string             `json:"summary"`
	Tags         []TagSnapshot      `json:"tags"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updatedAt"`
}

// RevisionViewReason defines model for RevisionView.Reason.
type RevisionViewReason string

// RevisionViewStatus defines model for RevisionView.Status.
type RevisionViewStatus string

// SaveDraftRequest defines model for SaveDraftRequest.
type SaveDraftRequest struct {
	ContentMd    string  `json:"contentMd"`
	CoverMediaId *int64  `json:"coverMediaId"`
	LockVersion  int64   `json:"lockVersion"`
	Summary      string  `json:"summary"`
	TagIds       []int64 `json:"tagIds"`
	Title        string  `json:"title"`
}

// SiteSettingsView defines model for SiteSettingsView.
type SiteSettingsView struct {
	AboutMd                string       `json:"aboutMd"`
	AuthorBio              string       `json:"authorBio"`
	AuthorName             string       `json:"authorName"`
	FilingName             string       `json:"filingName"`
	FilingNumber           string       `json:"filingNumber"`
	FilingUrl              *string      `json:"filingUrl,omitempty"`
	HomeStatus             string       `json:"homeStatus"`
	Id                     *int64       `json:"id"`
	LockVersion            int64        `json:"lockVersion"`
	SeoDefaultDescription  string       `json:"seoDefaultDescription"`
	SeoDefaultImageMediaId *int64       `json:"seoDefaultImageMediaId"`
	SeoDefaultTitle        string       `json:"seoDefaultTitle"`
	SiteName               string       `json:"siteName"`
	SocialLinks            []SocialLink `json:"socialLinks"`
	UpdatedAt              *time.Time   `json:"updatedAt"`
}

// SocialLink defines model for SocialLink.
type SocialLink struct {
	Label string `json:"label"`
	Url   string `json:"url"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []TagView `json:"items"`
}

// TagSnapshot defines model for TagSnapshot.
type TagSnapshot struct {
	Name     string `json:"name"`
	Position int    `json:"position"`
	Slug     string `json:"slug"`
	TagId    int64  `json:"tagId"`
}

// TagView defines model for TagView.
type TagView struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// VersionResult defines model for VersionResult.
type VersionResult struct {
	Draft   DraftView    `json:"draft"`
	Version RevisionView `json:"version"`
}

// ArticleId defines model for ArticleId.
type ArticleId = int64

// ReleaseId defines model for ReleaseId.
type ReleaseId = int64

// RevisionId defines model for RevisionId.
type RevisionId = int64

// TagId defines model for TagId.
type TagId = int64

// ArticleDetailResponse defines model for ArticleDetailResponse.
type ArticleDetailResponse = ArticleDetail

// ArticleListResponse defines model for ArticleListResponse.
type ArticleListResponse = ArticleList

// DraftViewResponse defines model for DraftViewResponse.
type DraftViewResponse = DraftView

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// SiteSettingsResponse defines model for SiteSettingsResponse.
type SiteSettingsResponse = SiteSettingsView

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	State *ListArticlesParamsState `form:"state,omitempty" json:"state,omitempty"`
}

// ListArticlesParamsState defines parameters for ListArticles.
type ListArticlesParamsState string

// ListReleasesParams defines parameters for ListReleases.
type ListReleasesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SaveArticleDraftJSONRequestBody defines body for SaveArticleDraft for application/json ContentType.
type SaveArticleDraftJSONRequestBody = SaveDraftRequest

// CreateArticleVersionJSONRequestBody defines body for CreateArticleVersion for application/json ContentType.
type CreateArticleVersionJSONRequestBody = LockVersionRequest

// RestoreArticleVersionJSONRequestBody defines body for RestoreArticleVersion for application/json ContentType.
type RestoreArticleVersionJSONRequestBody = LockVersionRequest

// PutBuilderConfigJSONRequestBody defines body for PutBuilderConfig for application/json ContentType.
type PutBuilderConfigJSONRequestBody = PutBuilderConfigRequest

// RegisterMediaJSONRequestBody defines body for RegisterMedia for application/json ContentType.
type RegisterMediaJSONRequestBody = RegisterMediaRequest

// CreateReleaseJSONRequestBody defines body for CreateRelease for application/json ContentType.
type CreateReleaseJSONRequestBody = CreateReleaseRequest

// LoginAdminJSONRequestBody defines body for LoginAdmin for application/json ContentType.
type LoginAdminJSONRequestBody = LoginRequest

// PutHotlinkSettingsJSONRequestBody defines body for PutHotlinkSettings for application/json ContentType.
type PutHotlinkSettingsJSONRequestBody = PutHotlinkSettingsRequest

// PutSiteSettingsJSONRequestBody defines body for PutSiteSettings for application/json ContentType.
type PutSiteSettingsJSONRequestBody = PutSiteSettingsRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// RenameTagJSONRequestBody defines body for RenameTag for application/json ContentType.
type RenameTagJSONRequestBody = RenameTagRequest

// AcceptJenkinsCallbackJSONRequestBody defines body for AcceptJenkinsCallback for application/json ContentType.
type AcceptJenkinsCallbackJSONRequestBody = JenkinsCallbackRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/admin/v1/articles)
	ListArticles(c *gin.Context, params ListArticlesParams)

	// (POST /api/admin/v1/articles)
	CreateArticle(c *gin.Context)

	// (GET /api/admin/v1/articles/{articleId})
	GetArticle(c *gin.Context, articleId ArticleId)

	// (PUT /api/admin/v1/articles/{articleId}/draft)
	SaveArticleDraft(c *gin.Context, articleId ArticleId)

	// (GET /api/admin/v1/articles/{articleId}/preview)
	GetArticlePreview(c *gin.Context, articleId ArticleId)

	// (POST /api/admin/v1/articles/{articleId}/trash)
	TrashArticle(c *gin.Context, articleId ArticleId)

	// (POST /api/admin/v1/articles/{articleId}/untrash)
	UntrashArticle(c *gin.Context, articleId ArticleId)

	// (GET /api/admin/v1/articles/{articleId}/versions)
	ListArticleVersions(c *gin.Context, articleId ArticleId)

	// (POST /api/admin/v1/articles/{articleId}/versions)
	CreateArticleVersion(c *gin.Context, articleId ArticleId)

	// (POST /api/admin/v1/articles/{articleId}/versions/{revisionId}/restore)
	RestoreArticleVersion(c *gin.Context, articleId ArticleId, revisionId RevisionId)

	// (GET /api/admin/v1/builder)
	GetBuilderConfig(c *gin.Context)

	// (PUT /api/admin/v1/builder)
	PutBuilderConfig(c *gin.Context)

	// (POST /api/admin/v1/builder/test)
	TestBuilderConfig(c *gin.Context)

	// (GET /api/admin/v1/me)
	GetCurrentAdmin(c *gin.Context)

	// (POST /api/admin/v1/media)
	RegisterMedia(c *gin.Context)

	// (POST /api/admin/v1/media/upload-policy)
	CreateMediaUploadPolicy(c *gin.Context)

	// (GET /api/admin/v1/releases)
	ListReleases(c *gin.Context, params ListReleasesParams)

	// (POST /api/admin/v1/releases)
	CreateRelease(c *gin.Context)

	// (GET /api/admin/v1/releases/{releaseId})
	GetRelease(c *gin.Context, releaseId ReleaseId)

	// (POST /api/admin/v1/releases/{releaseId}/retry)
	RetryRelease(c *gin.Context, releaseId ReleaseId)

	// (DELETE /api/admin/v1/session)
	LogoutAdmin(c *gin.Context)

	// (POST /api/admin/v1/session)
	LoginAdmin(c *gin.Context)

	// (GET /api/admin/v1/settings/hotlink)
	GetHotlinkSettings(c *gin.Context)

	// (PUT /api/admin/v1/settings/hotlink)
	PutHotlinkSettings(c *gin.Context)

	// (GET /api/admin/v1/settings/site)
	GetSiteSettings(c *gin.Context)

	// (PUT /api/admin/v1/settings/site)
	PutSiteSettings(c *gin.Context)

	// (GET /api/admin/v1/tags)
	ListTags(c *gin.Context)

	// (POST /api/admin/v1/tags)
	CreateTag(c *gin.Context)

	// (PATCH /api/admin/v1/tags/{tagId})
	RenameTag(c *gin.Context, tagId TagId)

	// (POST /api/internal/v1/jenkins/callback)
	AcceptJenkinsCallback(c *gin.Context)

	// (GET /api/internal/v1/releases/{releaseId}/bundle)
	GetReleaseBundle(c *gin.Context, releaseId ReleaseId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListArticles(c, params)
}

// CreateArticle operation middleware
func (siw *ServerInterfaceWrapper) CreateArticle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateArticle(c)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArticle(c, articleId)
}

// SaveArticleDraft operation middleware
func (siw *ServerInterfaceWrapper) SaveArticleDraft(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveArticleDraft(c, articleId)
}

// GetArticlePreview operation middleware
func (siw *ServerInterfaceWrapper) GetArticlePreview(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArticlePreview(c, articleId)
}

// TrashArticle operation middleware
func (siw *ServerInterfaceWrapper) TrashArticle(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TrashArticle(c, articleId)
}

// UntrashArticle operation middleware
func (siw *ServerInterfaceWrapper) UntrashArticle(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UntrashArticle(c, articleId)
}

// ListArticleVersions operation middleware
func (siw *ServerInterfaceWrapper) ListArticleVersions(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListArticleVersions(c, articleId)
}

// CreateArticleVersion operation middleware
func (siw *ServerInterfaceWrapper) CreateArticleVersion(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateArticleVersion(c, articleId)
}

// RestoreArticleVersion operation middleware
func (siw *ServerInterfaceWrapper) RestoreArticleVersion(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", c.Param("articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter articleId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "revisionId" -------------
	var revisionId RevisionId

	err = runtime.BindStyledParameterWithOptions("simple", "revisionId", c.Param("revisionId"), &revisionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter revisionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RestoreArticleVersion(c, articleId, revisionId)
}

// GetBuilderConfig operation middleware
func (siw *ServerInterfaceWrapper) GetBuilderConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuilderConfig(c)
}

// PutBuilderConfig operation middleware
func (siw *ServerInterfaceWrapper) PutBuilderConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutBuilderConfig(c)
}

// TestBuilderConfig operation middleware
func (siw *ServerInterfaceWrapper) TestBuilderConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestBuilderConfig(c)
}

// GetCurrentAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentAdmin(c)
}

// RegisterMedia operation middleware
func (siw *ServerInterfaceWrapper) RegisterMedia(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterMedia(c)
}

// CreateMediaUploadPolicy operation middleware
func (siw *ServerInterfaceWrapper) CreateMediaUploadPolicy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMediaUploadPolicy(c)
}

// ListReleases operation middleware
func (siw *ServerInterfaceWrapper) ListReleases(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReleasesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListReleases(c, params)
}

// CreateRelease operation middleware
func (siw *ServerInterfaceWrapper) CreateRelease(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRelease(c)
}

// GetRelease operation middleware
func (siw *ServerInterfaceWrapper) GetRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "releaseId" -------------
	var releaseId ReleaseId

	err = runtime.BindStyledParameterWithOptions("simple", "releaseId", c.Param("releaseId"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter releaseId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRelease(c, releaseId)
}

// RetryRelease operation middleware
func (siw *ServerInterfaceWrapper) RetryRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "releaseId" -------------
	var releaseId ReleaseId

	err = runtime.BindStyledParameterWithOptions("simple", "releaseId", c.Param("releaseId"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter releaseId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RetryRelease(c, releaseId)
}

// LogoutAdmin operation middleware
func (siw *ServerInterfaceWrapper) LogoutAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LogoutAdmin(c)
}

// LoginAdmin operation middleware
func (siw *ServerInterfaceWrapper) LoginAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginAdmin(c)
}

// GetHotlinkSettings operation middleware
func (siw *ServerInterfaceWrapper) GetHotlinkSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHotlinkSettings(c)
}

// PutHotlinkSettings operation middleware
func (siw *ServerInterfaceWrapper) PutHotlinkSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutHotlinkSettings(c)
}

// GetSiteSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSiteSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSiteSettings(c)
}

// PutSiteSettings operation middleware
func (siw *ServerInterfaceWrapper) PutSiteSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutSiteSettings(c)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTags(c)
}

// CreateTag operation middleware
func (siw *ServerInterfaceWrapper) CreateTag(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTag(c)
}

// RenameTag operation middleware
func (siw *ServerInterfaceWrapper) RenameTag(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "tagId" -------------
	var tagId TagId

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", c.Param("tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RenameTag(c, tagId)
}

// AcceptJenkinsCallback operation middleware
func (siw *ServerInterfaceWrapper) AcceptJenkinsCallback(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptJenkinsCallback(c)
}

// GetReleaseBundle operation middleware
func (siw *ServerInterfaceWrapper) GetReleaseBundle(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "releaseId" -------------
	var releaseId ReleaseId

	err = runtime.BindStyledParameterWithOptions("simple", "releaseId", c.Param("releaseId"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter releaseId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReleaseBundle(c, releaseId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/api/admin/v1/session", wrapper.LogoutAdmin)
	router.POST(options.BaseURL+"/api/admin/v1/session", wrapper.LoginAdmin)
	router.GET(options.BaseURL+"/api/admin/v1/me", wrapper.GetCurrentAdmin)
	router.GET(options.BaseURL+"/api/admin/v1/articles", wrapper.ListArticles)
	router.POST(options.BaseURL+"/api/admin/v1/articles", wrapper.CreateArticle)
	router.GET(options.BaseURL+"/api/admin/v1/articles/:articleId", wrapper.GetArticle)
	router.PUT(options.BaseURL+"/api/admin/v1/articles/:articleId/draft", wrapper.SaveArticleDraft)
	router.GET(options.BaseURL+"/api/admin/v1/articles/:articleId/preview", wrapper.GetArticlePreview)
	router.GET(options.BaseURL+"/api/admin/v1/articles/:articleId/versions", wrapper.ListArticleVersions)
	router.POST(options.BaseURL+"/api/admin/v1/articles/:articleId/versions", wrapper.CreateArticleVersion)
	router.POST(options.BaseURL+"/api/admin/v1/articles/:articleId/versions/:revisionId/restore", wrapper.RestoreArticleVersion)
	router.POST(options.BaseURL+"/api/admin/v1/articles/:articleId/trash", wrapper.TrashArticle)
	router.POST(options.BaseURL+"/api/admin/v1/articles/:articleId/untrash", wrapper.UntrashArticle)
	router.GET(options.BaseURL+"/api/admin/v1/tags", wrapper.ListTags)
	router.POST(options.BaseURL+"/api/admin/v1/tags", wrapper.CreateTag)
	router.PATCH(options.BaseURL+"/api/admin/v1/tags/:tagId", wrapper.RenameTag)
	router.POST(options.BaseURL+"/api/admin/v1/media/upload-policy", wrapper.CreateMediaUploadPolicy)
	router.POST(options.BaseURL+"/api/admin/v1/media", wrapper.RegisterMedia)
	router.GET(options.BaseURL+"/api/admin/v1/settings/site", wrapper.GetSiteSettings)
	router.PUT(options.BaseURL+"/api/admin/v1/settings/site", wrapper.PutSiteSettings)
	router.GET(options.BaseURL+"/api/admin/v1/settings/hotlink", wrapper.GetHotlinkSettings)
	router.PUT(options.BaseURL+"/api/admin/v1/settings/hotlink", wrapper.PutHotlinkSettings)
	router.GET(options.BaseURL+"/api/admin/v1/builder", wrapper.GetBuilderConfig)
	router.PUT(options.BaseURL+"/api/admin/v1/builder", wrapper.PutBuilderConfig)
	router.POST(options.BaseURL+"/api/admin/v1/builder/test", wrapper.TestBuilderConfig)
	router.GET(options.BaseURL+"/api/admin/v1/releases", wrapper.ListReleases)
	router.POST(options.BaseURL+"/api/admin/v1/releases", wrapper.CreateRelease)
	router.GET(options.BaseURL+"/api/admin/v1/releases/:releaseId", wrapper.GetRelease)
	router.POST(options.BaseURL+"/api/admin/v1/releases/:releaseId/retry", wrapper.RetryRelease)
	router.GET(options.BaseURL+"/api/internal/v1/releases/:releaseId/bundle", wrapper.GetReleaseBundle)
	router.POST(options.BaseURL+"/api/internal/v1/jenkins/callback", wrapper.AcceptJenkinsCallback)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D3bcts6kr/C4s7b0Jbs2JkTz1NOLjM5cyabsp3U1qa8KYhsUbBJgAFAO4rL/76FC0mQAiWSutie6M0W",
	"CaDR6Hs3mvd+SNOMEiCC+2f3foYYSkEAU/+9ZgKHCXyI5D+Y+Gd+hsTMD3yCUvDPfFQ+D3wG33PMIPLP",
	"BMsh8Hk4gxTJgVPKUiT8Mx8T8fLED/wUE5zmqX92FPhinoF+BDEw/+Eh8M8hAcTbV2Xl882ueos5pmTJ",
	"suULm1z3EsWtSwr1bHOrPcipeEYJB/t834JAODk3T+SDkBIBRMg/UZYlOEQCUzK65pTI36r1/8Jg6p/5",
	"/zWqyGikn/JRbXa9egQ8ZDiTk/lnxfIeIpEX5owBER5EWGASexFDU+E/BMVLf2IutgWhnHsJfNzDxJNP",
	"gEQStDyLkACPskgiNfDfSlC/YLjbOHzlzC7o3rRh7BOjkwTSDtBk+s2/9oPKzO+C6Ry+58CFN0U4gUgC",
	"c4EFXICQEPKN48eevA1Nn/JJgvkMTRLwOBbgcTNAcZ+ZSTFDlGKiZpEwRRKrlKDkE6MZMIElx0xRwiHw",
	"M+unex9HvRkx8HMOTDP5ffGUC4ZJ7GsmLfj9q5zeev2qnIxOriG0OcTwWT/gQwZIQPRa1PYg6ftA4BT8",
	"oAld4Gs66065ZkRdvvZE1yAcZ/rkIeqxNMmTRJJKIWkXZ+VJHjtOLfC5QEKdJxA52VcfhQLfKhQyJMGw",
	"Dq8apYVJjwNwkYeCaRHPbhQUkAbW4dtwFCe8hNSUwOzJJQLS+h8dBPNFnqaIzeXKBhTEGJovIkHNuQTg",
	"YqLdMMdapK5muMQiASeVqcef+xLNnoO2w0HWYS0cTRt/ucj09xwnEbA3lExxPEAHTRCHzyypYSBn2EUI",
	"QOTpRNYBTChNAJHBVHJNJx/dqqwwZB0PBL0BovebszZwempJ9WpQIsMaXwFZIWARBvfJkCgBI0Z6ngqy",
	"3aeeSDX20T8Rn2m/TAhg0p75Pz5Dx6cvz76OD16hg+nV/cuTh7+4DtrM8G/EbiJ6R5ynUFJ3H1HC1hFv",
	"BfOnmPwJJBYz+z1LFFQCe5F0UFzXJCvmqquOwBctwrVBUnXn1mZ+LSuEYfsC1EWM10+xjm2zjXaSk7Zt",
	"X3qb0Hz5eaNczCj7HVPn0ylOMIlbedk8ztMJsH7MzmmIUfInJjfdTYCLcsxK9W9YvNpc0EBFbWuNjdSh",
	"az+PSxTvwjFox2EXxlkiFdV41/beKC1lgi7GgduaoFttHaQ0qtkAhmm+mTWkVCeLvxW/lM7d1SrcqHUC",
	"C/QOuOF50hc113Sy0p/WsP9BJ4XDZCJcqwYauIznW99eMYXSfEv2doniYWdeEGqKfhT0+PIk6EWerR5t",
	"5T0+msJtVadRy9NbYP+GCKONMMEAz2OQtEloePMFGMc66tJzdCr321mgK+ycwxQYkBDUePTjgx55fPq3",
	"RT3NAJloUCELmo7pok3ykQ6xSQQSObcXMjE151K9TJNlCLlE8QVBGZ9RUcfGi+PuRsuG/B+XsfNRKlKb",
	"QkpMlWfjtoIsVrD5pmkOKWQVVNTHW/onFQkmN++I6O3SL/V+ZpSLbu5G+WblTiwBtBai7CnRkoTevUsz",
	"Mdecw9yQAxGsGWhZRno1DK4yrxZhqBZ07foPIDeY8DcoSSYovBmmXibSI65szXaOHrs4GhijzAr6WErq",
	"9OjYwdSESplUd7S+vj74X3Twc3zw6tvB1f3Ry+Do+De3q8XsjFV/4RP3VqQumfU9h1y5tQp18rXAjyBL",
	"6Fz/zfMwBC45zkTnXcJNSgwuUJoNFCZ2bs4+wmKflgipnZG9cnEaLtr6sxJHw+hqHY3X2Ks9lRvWGA+E",
	"MkOc31Gm6Kmezvh8+f7gNw9ISCOIvFuU5OClORfeBDwkvJRy4R2fvvQmcwH80A9ssjo+fbmSruyQyxqm",
	"nRV5KffiwlHDKOiHpbSjveUIbFKOhSGB5ZJEORbhv2DeEj9hGeU1f0Wpv0rXdXBESlVZrVXNbMHair/P",
	"WUJR9IkmOOyrD1GWfXBbtPAjw6w1EADvMSTugaUoXcRWCeGiOMMxQSJvWbAmlRwGkNx+p/Bnk0rLkYHB",
	"RAmkDVJdOBnEFBu10dF6QgM0/wAXQAJygX/CAIaIp/w9Hug5zQDHM1Fjpc0l8VKcwqX6tWIxnKIYRtcZ",
	"SLWm/8lI9fcdTLLynxhPnYqOMhxjgpLWaNdyxm9LVWwkQRH4uSZmyxgZ4TQeZYz+mI++lkbJX53WyB2O",
	"xGzVcbicAFv+VATRwJV1JBbFFauW1FDlSHLFXt2t+0/S/4C7ASzTPzNdBNVsq88y+Y5d5l4Dc3bmqGU/",
	"ulyiJ/ubMJjD1lQGRYvUrszCRVZqdyGFYbBewlNoEigdwMKuC3VgrYLTiZR6zGtLvkGnWMtE596GBY36",
	"C+nerskUk1UpmpZNrhkc2ohX08FxyXRdlR9swoVxybUFp0SdtkWyhW9S91gaDootwawzcVO3qGV0B7rA",
	"rUld26Yfn/zWN8trJWytmY6Of1vpHTg8g6PxeOUwlWhtjDsZv1rhjQT+HcMC/pskc03Y7e7J8enpgNBz",
	"51Rxyxk3wjsDcyfPMMLzKRf1ur5BG1cpuqh5kuNXfzs6dcnB5blL/XRV7nJwanNGU7ho6tbqceeogtPH",
	"5EDfwhTliXhr+/ou4Vm++UFat5tLOFQTt5cecSzg4/ZSvFX8++jlCnptBKULuGpUUM8HW+cXlJRXh3oR",
	"CW0n03oOy/LMLj46hxhzYaLlw7hoHcet6QOtI1Bb/QX3vpVC1on1YTm+7lRWr+Bx1IOEMwhveJ4OrLOJ",
	"gQDrawWuZVupjVnixhhSR1fOt00dyWoUqYqTvkmsqjhilZKpg123ymwcGpDL/FB54NZJLSGqrdem1rLu",
	"gwtT7Vl6eobrkavcUQJiPX9iV/npazrhizHwN2YLHgPB5t4Mc0HZXF/IgMibzL0SPuveRuCJGRAPR9Zv",
	"h37Q7dAXazRSTAp1tShSEiSAiz+G1H4sSewMdH8qz7ygnLozY1OEDbpBv5t6pa38JGtHziVN9KvYqVPX",
	"5UwSlhrvYS6Jxtz4iTwUxwxiJODvxRuHJbrULabiV4m4r+MrD77nKPGu6UQS2nMpDCoqnXcgSfVCa4tS",
	"a5p9wdC+YKgSnSkiOUq+3ZZGR1knWBTe7KCYaMroTyD7WqInWUt0gW7hrb71MUST1Zi8Uxhjw4y/HkOu",
	"oL8PUZ0C+7J7OxUGfk7w9xzMcxPd61iZX6ejXlRjNuWkhOZl0sHhrKcVutIvuAPJDFBUxVeD3nEvvFMS",
	"3gfPBgXPuoj1FR6fS8w/xyCczQ0rNUOF4J4lZmgCiVu9DqhR0bPpsS4wL1G8dUP9EsVr2ui2fTLMV3RU",
	"E3Wt4Wq9cCqK3hvrlAEWTTrsezYrqrYKfG69Img7V5C2YzbW8dfdgivLQQfczulfMXJbKarurm1ju5U7",
	"0lY1opRKmDMs5hdyRqg6VFwALwBQHWNCSm8wVD1jvv/4Nklo/I2b9yqWzfC/YG5daCuSsgpmlW4EpHN/",
	"ZsRMiMwq6L6wa/TU2jNAkRpg1v6fA/PqwYVdPFdfX24Ok6m2hbS+9L/j/Ac/kHB7apPe608ffAvZ/tHh",
	"+HCschYZEJRh/8x/cTg+fKHqS8VMoWeEMjxCcvjo9mhk5wliUIcsT161GZFM70up+bqKLdudj76a/X3P",
	"QRmUZntFRVPVnCTS+kfurriq3uPu+sNVox/P8XjcRljleyNXQ5yHwD/pMrbZGkaNOxo07nT8YsA4i7AV",
	"musk/fXq4UpLdsd56ftqr8srfw3MHXXGXKPd0SPg7mQQ7uS4V0/rrB6CFq4b3ZdRgIdWDvwHiNbjHD+r",
	"4zx5cixUl2auJapXRlWfNzV49ZGOSsU5fKHAz3IHUVyg24LJleKtSgl/p9F8c62jmnGfh7qWNhGJ/lS5",
	"2A3sWQmYk50KppPj42co0EaZLlHuINhMMXOLfNsIJdv10kvaxCmO9QrI91JyF1JSmX5rS0mnNXQpp27V",
	"nieLSfOi2WJKbyHyBPU0cHvh9FSFTE62SD6f9eRDCIgBF5RB5E0ZTfdU9MSpyLjQndzgL8W7W9RWteIC",
	"h7p6r5KlHiqJTb/O9xprTY3Vya22q/M2b3M7Lm93srqPNgZBPVbYTn6Ga0xNT5agEFJnr9291PuPMuwL",
	"aTm6rzq+PYyMxltLEwcrX7YaTLZz67kG5Umz695J/tV4yVyqW+YP1+7DbdPAWGylusQpNukKz2zAC00z",
	"ULWwd4fFjObCU9fXvBQJYBgle0tEWyKu4F3z4uOWJFPb/cru4ml3pHaBpL/9fAjtxV62uWTbSJjiwJZw",
	"jCTx5SLO4VIXVBFSQiBUpIDCEDKhv53wbA7/6Kkfoi5oaNNNRhuoibapmqovTCxRSQpmzAVDgrInmaB1",
	"YNeUdbfZrNYtxy1pBOdNyh07l1WnH8fxfgGGpxikO6khhcjTeNtL+adCwiPdD+qg6lO1LGSy2Hpri6Jj",
	"cTGXqTGjTBwkWBocEWYQCu8f7y88vSvP7OoZkdvujt9ciloeJT0vXupULJTgFAt3sdDxWBXsmhI80z9j",
	"SbmhewE6nXJoWWG8vGq6rfBoQ6K4uofrINIPaZoL9TWm4pJdeauOO65wfkPCe/vu4k3g4Uj9cfgLFTud",
	"l3f1tqEznY3fO+nM423B0BaWdRCNsZO9KWUeV/6Sp/uXKTB+Ca365M3uQqyO7svL/kurwWx63650ajPT",
	"FgmNQUhZtA/6DEg/VR/ydBRMuGhjpC7094+z2wu1R86re+H+FiWa4/65g84+wp1n7qJ613SipJiYgcdR",
	"Ch5uEuE+Ov6cpSCvKvYjSEC3Y2mYlzSmeVsAwhE4Mit6DHQ5D2UeShigaO6hCZc0/Mhmd7tlo7piVzvd",
	"RtrKaru944jw0gjP61zMgAg5M0SuOM8zYfDjnRbCuPhJX9IdzXSPu2UWRaNF3zYtC9fHHpbE+Qzwj+iW",
	"P0JyyHUcW0kPtbRm3LE46EgS57rCJHoCNLGPDLZKm6KRWpuosfsHDLrP4vxU9q8hFxZwtxWh4OpZuqmK",
	"lqdyeHsGbjJw0UenNa57ibZrGBQ39B2SXy7tYeJx7e5FmGcJMp3sfqE45yWKtxrjtBrV7TgnWHZOcBiC",
	"OsDtCd07c38HdZMMP7pXbRke+seSLlU7BxVHQiKcuQJJpvfh1lLZjd6KOzZal5CsBu0Zkux/2JUPTAQw",
	"ghJJ7de6hmgUms/ttaetX6uUSePrfFsi4pZvAHYiZUe8q5inSvvYES8J5WNVTD0mhSz25WilEme0fVL2",
	"316RkDGNurefljELdUrMaOj/7qVo7uUcvDcajoN3JKQRJrEX/8SZ+iARipTsv/ffmY94VzAt9qX5Yvrh",
	"tb/z8IxyQY9LoLVGM+unkNT07LYYqrppqSY1/Gw0miQ0PlA2wKHqJnMY0lQO+v8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
