-- qiuxs-blog development SQL.
-- Reviewed and executed manually. Do not run from service startup.
-- All table IDs are generated by Redis idgen before INSERT.

CREATE TABLE admins (
    id BIGINT NOT NULL,
    singleton_key TINYINT NOT NULL DEFAULT 1,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'active',
    last_login_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admins_singleton (singleton_key),
    UNIQUE KEY uk_admins_username (username),
    CONSTRAINT chk_admins_singleton CHECK (singleton_key = 1),
    CONSTRAINT chk_admins_state CHECK (state IN ('active', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
